### ISSUE TITLE
安装文档配置有文件错误

### ISSUE THREAD

**Issue by potapotato** [NixOS-CN/nixos-cn.github.io#13]
在修改 `/mnt/etc/nixos/configuration.nix` 文件时发现很多错误
- `networking.hostnName = "nixos";`  应该修正为 `networking.hostName = "nixos";` 
-  `services.xserver.displayManager.sddm = true;` 应该改为 `services.xserver.displayManager.sddm.enable = true;`
- `services.xserver.desktopManager.plasma5 = true;` 应该改为 `services.xserver.desktopManager.plasma5.enable = true;`
- `enviroment.systemPackages` 应该修正为 `environment.systemPackages`
- `vim,` 中的逗号应该去掉

在`由于生成配置命令没有写入 Btrfs 子卷的挂载参数，我们需要自己修改另一个配置文件：` 这里修改配置文件的命令 `vim /mnt/etc/nixos/configuration.nix` 是错的，应该是 ` vim /mnt/etc/nixos/hardware-configuration.nix` 

截至 2023/10/06 号发现的，修改后就能正常安装了。

**Comment by potapotato** [comment]
补充一下，是虚拟机安装部分

**Comment by OpenTritium** [comment]
是我粗心了呜呜，感谢你的提交，我计划今天一起修改了。

**Comment by OpenTritium** [comment]
已经修正了，如果我没有再粗心一次应该是对的了（
