### ISSUE TITLE
如何完善「Nix 语言」部分的内容

### ISSUE THREAD

**Issue by ryan4yin** [NixOS-CN/nixos-cn.github.io#18]
我目前有想法帮助完善下 NixOS-CN 的「Nix 语言」这一部分。

先介绍下背景，我是 [nixos-and-flakes-book](https://github.com/ryan4yin/nixos-and-flakes-book) 的作者，之前我也写了个很简单的 Nix 语言入门教程，大部分内容是对 nix.dev 语言入门部分的简要翻译。

然后我近期发现 NixOS-CN 的「Nix 语言概览」写得挺好，出于降低我个人的维护负担以及避免重复造轮子的目的，我已经将我写的内容移除，并给读者指路到了 NixOS-CN: https://github.com/ryan4yin/nixos-and-flakes-book/commit/47b905a5c487a5312208ad548d29dc85579d71ab

但目前我看到， NixOS-CN 的「Nix 语言」部分仍然很不完善，我已经提了 #16 与 #17 两个 PR 补充了些内容，但是感觉还需要做些沟通，才能确定我接下来要如何贡献内容。

**Comment by OpenTritium** [comment]
感谢你的 PRs，我早就阅读过你的大作哈哈，非常欢迎你的加入。我自己也是花了不到一个月的时间编写了了基础的页面，但是个人精力始终不够分配，并且现在我是面临毕业压力与求职压力等，暂时心累。你的到来是我们的幸运，我对你的加入乐意至极。

**Comment by OpenTritium** [comment]
我自己对 nixos 的学习并不深入，并且我现在也没有使用 nixos 了，但我仍可能在未来使用它。我并不了解 nix 生态最时髦的部分，导致翻译了部分历史包裹。你可以赋予这个文档站新的生命（我的意思是，你可以更主动地实现你的主见，当然是你愿意交接这个仓库的话）。

**Comment by OpenTritium** [comment]
我又重新读了你的话，你原本的意思是减少造轮子的经历，结果我现在还想将这东西托付给你，好像更怪了LOL

**Comment by ryan4yin** [comment]
感谢回复，我觉得你写的内容有些很好的东西，这也是我想为它做贡献的初衷。
让我来接手也是可以的，但有个问题是，它跟我的 nixos & flakes book 会有一定重复。
我的 book 目前是双语的，并且英文读者明显更活跃、更愿意给项目提 issues, PRs 或评论。

这样的话，我的思路会是，nixos-cn 站只写些英文世界不缺的内容，比如语言教程、国内特有的网络环境的坑等等。而英文世界也可能会需要的内容，我会将他们迁移到我的 book，并同时添加英文版。

不知道这样的想法你觉得如何?
