### ISSUE TITLE
使用双协议

### ISSUE THREAD

**Issue by CyrusYip** [nixos-cn/nixos-cn.github.io#2]
目前本仓库使用 GPL3 协议，但是一般文本内容都用 Creative Commons 协议。可以参考[NixOS官方](https://github.com/NixOS/nixos-homepage/tree/master/LICENSES)双协议的做法，代码使用 MIT，文本使用 CC-BY-SA-4.0 协议（需要署名、修改后需要以相同协议公布、可商用）。Nix Pills 和 nix.dev 也是使用 CC-BY-SA 协议。

**Comment by OpenTritium** [comment]
支持以上看法。

**Comment by CyrusYip** [comment]
赞同 MIT + CC BY SA 协议的请在这点赞，有其他意见也可以发。

**Comment by CyrusYip** [comment]
@OpenTritium 请问哪些文件夹是文本内容？写说明文件的时候要提及一下。

**Comment by CyrusYip** [comment]
我已经提交修改协议的 Pull Request https://github.com/nixos-cn/nixos-cn.github.io/pull/3 。

**Comment by OpenTritium** [comment]
> @OpenTritium 请问哪些文件夹是文本内容？写说明文件的时候要提及一下。`/src` 文件夹里除了 `.vuepress` 都是文档吧。

我会在后续的提交中添加根目录 README 文件来描述大概的目录结构。
