### ISSUE TITLE
关于设置的prettier提供的格式化导致前后布局差异化的建议

### ISSUE THREAD

**Issue by TatooiNoyo** [NixOS-CN/nixos-cn.github.io#30]
这是经由prettier格式化后的布局
![swappy-20240624_145737](https://github.com/NixOS-CN/nixos-cn.github.io/assets/98942281/67e5bdd7-3637-49bb-a5d5-1aa219cdeb14)

这是未经prettier格式化后的布局
![image](https://github.com/NixOS-CN/nixos-cn.github.io/assets/98942281/5c503662-babb-4fe0-8a5b-365b8eb296ff)

两者的排版差异明显，已有的布局未经由prettier格式化。是否考虑关闭prettier格式化或~~调整prettier格式化配置~~调整项目渲染markdown的行为？

**Comment by linyinfeng** [comment]
经典的在 Markdown 里用 CJK 会遇到的问题。

通常的 markdown 实现多行文字中间的换行是 softbreak，将这些换行渲染成 HTML 里的换行，这样对英文是合适的。这使得 markdown 源码可以随意换行，所以 prettier 也是这么做的。
<https://spec.commonmark.org/0.31.2/#soft-line-breaks>

但是这样对中文来说不合适，因为 HTML `<p>` 内的换行会被渲染成空格，会导致多出来空格。看起来本站的渲染是全当作 hard line break，将换行渲染成 `<br>`，但这样就导致 prettier 加入的换行被渲染出来了。

Pandoc 有个 `east_asian_line_breaks` 扩展去解决这问题，不知道 vuepress 有没有类似的东西。我搜了一下，看到一个 `markdown-it` 插件： <https://github.com/markdown-it/markdown-it/issues/334#issuecomment-368194267>.

**Comment by TatooiNoyo** [comment]
项目中配置的[gfm](https://github.com/NixOS-CN/nixos-cn.github.io/blob/main/src%2F.vuepress%2Ftheme.ts#L47)自动启用了
[breaks](https://plugin-md-enhance.vuejs.press/zh/config.html#breaks)。
这似乎是渲染markdown时使用硬换行的原因。

**Comment by TatooiNoyo** [comment]
> 经典的在 Markdown 里用 CJK 会遇到的问题。
> 
> 通常的 markdown 实现多行文字中间的换行是 softbreak，将这些换行渲染成 HTML 里的换行，这样对英文是合适的。这使得 markdown 源码可以随意换行，所以 prettier 也是这么做的。 https://spec.commonmark.org/0.31.2/#soft-line-breaks
> 
> 但是这样对中文来说不合适，因为 HTML `<p>` 内的换行会被渲染成空格，会导致多出来空格。看起来本站的渲染是全当作 hard line break，将换行渲染成 `<br>`，但这样就导致 prettier 加入的换行被渲染出来了。
> 
> Pandoc 有个 `east_asian_line_breaks` 扩展去解决这问题，不知道 vuepress 有没有类似的东西。我搜了一下，看到一个 `markdown-it` 插件： [markdown-it/markdown-it#334 (comment)](https://github.com/markdown-it/markdown-it/issues/334#issuecomment-368194267).

我尝试显示关闭markdown的breaks增强功能后，发现不需要引入新的插件配置亦可达到预期效果。

**Comment by ryan4yin** [comment]
> 两者的排版差异明显，已有的布局未经由prettier格式化。是否考虑关闭prettier格式化或~调整prettier格式化配置~调整项目渲染markdown的行为？ -- @TatooiNoyo 

我的锅，prettier 格式化配置是我之前添加的，当时没做好 cjk breaks 的处理以及所有文档的统一格式化，导致了这个问题


> 我尝试显示关闭markdown的breaks增强功能后，发现不需要引入新的插件配置亦可达到预期效果。

👍 可以提个简单的 PR，我这边也测下，没问题的话就这么处理吧。

**Comment by TatooiNoyo** [comment]
> > 我尝试显示关闭markdown的breaks增强功能后，发现不需要引入新的插件配置亦可达到预期效果。
> 
> 👍 可以提个简单的 PR，我这边也测下，没问题的话就这么处理吧。

大面积格式化后测试，发现出现下述问题：
> 但是这样对中文来说不合适，因为 HTML `<p>` 内的换行会被渲染成空格，会导致多出来空格。看起来本站的渲染是全当作 hard line break，将换行渲染成 `<br>`，但这样就导致 prettier 加入的换行被渲染出来了。

似乎仍需要引入：
> Pandoc 有个 `east_asian_line_breaks` 扩展去解决这问题，不知道 vuepress 有没有类似的东西。我搜了一下，看到一个 `markdown-it` 插件： [markdown-it/markdown-it#334 (comment)](https://github.com/markdown-it/markdown-it/issues/334#issuecomment-368194267).

**Comment by ryan4yin** [comment]
vitepress 中是有类似这样的结构用于处理 cjk breaks: https://github.com/ryan4yin/nixos-and-flakes-book/blob/main/docs/.vitepress/config.ts#L78, 但 vuepress 2.0 我没找到类似的文档，我也不太懂前端，这东西要如何引入是个问题...

**Comment by TatooiNoyo** [comment]
已修复，可测试。
