### ISSUE TITLE
有关于`开发环境部署`的页面优化请求

### ISSUE THREAD

**Issue by jackyliu16** [NixOS-CN/nixos-cn.github.io#7]
近来，在阅读`Haskell 开发环境部署`文章时，显示如下情况，感觉有两个页面元素的地方可以适当优化：
1. 左侧的大标题和右侧的小标题实际上在内容上是重合的，个人感觉减少一个或者将左侧的替换成其他内容会更好
2. 左侧的标题字符过大，间距也挺大的，没有一些美化可能感觉怪怪的

![image](https://user-images.githubusercontent.com/50787361/224682544-26468d8f-1ad2-47a0-9ee9-f555ef414960.png)

**Comment by OpenTritium** [comment]
嗯我最初也是这样觉得的，已经收到提案，会在下次提交改善效果

**Comment by OpenTritium** [comment]
我已经在新的提交中更改了侧边栏样式，你觉得怎样？

**Comment by OpenTritium** [comment]
可能是浏览器缓存问题？本站点开启了pwa，现在可以被安装到奇奇怪怪的地方，清除缓存试试？这次主要是更改了左边导航栏跟右边概览重复的问题

**Comment by CyrusYip** [comment]
@OpenTritium 我看 nixos-cn.org 需要按 `Ctrl F5` 强制刷新才能看到最新页面。是因为 PWA 吗？每次看都要自己手动强制刷新，不同方便。

**Comment by OpenTritium** [comment]
> > 可能是浏览器缓存问题？本站点开启了pwa，现在可以被安装到奇奇怪怪的地方，清除缓存试试？这次主要是更改了左边导航栏跟右边概览重复的问题
> 
> 我感觉左边现在的效果还是很不错的，右边栏目这个地方可能稍微还有点可以改进的地方，删除这个右边的拉动栏可能会更好？
> ![image](https://user-images.githubusercontent.com/50787361/226658065-ca3c0438-ae56-4e63-8832-85c61ad2268d.png)
> 

这个是主题提供的，我可能有点无能为力（

**Comment by OpenTritium** [comment]
> @OpenTritium 我看 nixos-cn.org 需要按 `Ctrl F5` 强制刷新才能看到最新页面。是因为 PWA 吗？每次看都要自己手动强制刷新，不同方便。

你看看现在缓存问题改善了吗

**Comment by CyrusYip** [comment]
@OpenTritium 官网没有更新内容，我也不知道它有没有自动刷新缓存。

**Comment by OpenTritium** [comment]
> @OpenTritium 官网没有更新内容，我也不知道它有没有自动刷新缓存。

啊其实更新了，你可以看看安装手册
